name: Doc

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Doxygen
      run: sudo apt-get install -y doxygen
    - name: make doc
      run:  make doc -C movie/
