name: Doc

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Doxygen
      run: sudo apt-get install -y doxygen
    - name: make doc
      run:  make doc -C movie/
    - name: Commit files
      run: |
        git config --local user.email "alenvgeorge98@gmail.com"
        git config --local user.name "alenvgeorge"
        git commit -m "Add changes" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
